#include "physics.h"
#include <algorithm>
#include <cassert>
#include <iostream>

static Eigen::Index last_edge(Eigen::Index i) { return i; }
static Eigen::Index next_edge(Eigen::Index i) { return i+1; }

LineModel::LineModel(const DiscreteLine& line, 
                     const Vec2 anchor_left, 
                     const Vec2 anchor_right, 
                     const Params& p)
   : line_(std::move(line)),
     anchor_left_(anchor_left),
     anchor_right_(anchor_right),
     params_(p),
     has_slackliner_(false),
     node_slackliner_(-1),
     m_(line_.node_mass)
{
}

// TODO move to driver!
int LineModel::nearest_node(const Vec& q, const double x_coor) const {

   // Nearest free node in x to the slackliner
   Eigen::Map<const Mat2X> Q(q.data(), 2, q.size() / 2);
   Eigen::Index nearest;
   (Q.row(0).array() - x_coor).abs().minCoeff(&nearest);
   return static_cast<int>(nearest);

}

void LineModel::place_slackliner(const int node, double mass) const {
   if (has_slackliner_) remove_slackliner();

   assert(node >= 0 && node < line_.num_nodes());
   assert(mass > 0);

   has_slackliner_ = true;
   node_slackliner_ = node;
   m_[node_slackliner_] = line_.node_mass[node_slackliner_] + mass;
}

void LineModel::remove_slackliner() const {
   if (!has_slackliner_) return;

   has_slackliner_ = false;
   m_[node_slackliner_] = line_.node_mass[node_slackliner_];
}



// dq = qb - qa for edge e, which runs from node e-1 to node e.
// Node -1 is anchor_left_ and node q.cols() is anchor_right_.
Vec2 LineModel::edge_vector(CRef<Mat2X> q, Eigen::Index e) const {

   const Eigen::Index num_nodes = q.cols();
   assert(e >= 0 && e <= num_nodes);

   const Vec2 qa = (e == 0)         ? anchor_left_  : Vec2(q.col(e - 1));
   const Vec2 qb = (e == num_nodes) ? anchor_right_ : Vec2(q.col(e));

   return qb - qa;
}

  Vec2 LineModel::edge_force(Eigen::Index e, const Vec2& dq, Mat2* K) const
{
   const double len = dq.norm();
   const double s_main = len - line_.l_main[e];
   const double s_backup = len - line_.l_backup[e];
 
   double T = 0.0, dT = 0.0;   // tension, and dT/dlen
   if (s_main > 0.0)   { 
      T += line_.k_main[e] * s_main;   
      dT += line_.k_main[e]; 
   } 
   if (s_backup > 0.0) { 
      T += line_.k_backup[e] * s_backup; 
      dT += line_.k_backup[e]; 
   }
     
   // === Jacobian ===
   if (T == 0.0) {                 // slack edge
      if (K) K->setZero();
      return Vec2::Zero();
   } 
 
   const Vec2 u = dq / len; // Unit vector
   if (K) {
      Mat2 uuT = u * u.transpose();
      *K = T/len * (Mat2::Identity() - uuT) + dT * uuT;
   }
   
   return T * u;
}

// Fills net forces into F (and Jacobian if argument present)
void LineModel::assemble(CRef<Mat2X> q, Ref<Mat2X> F, SymmBlockTriMat* K) const
{
   const Eigen::Index num_edges = line_.num_elements();
   const Eigen::Index num_nodes = q.cols();
   const Vec2& g = params_.gravity;

   assert(num_edges > 1);

   Mat2 last_edge_K, next_edge_K;
   Mat2* last_edge_Kptr = nullptr; 
   Mat2* next_edge_Kptr = nullptr;
   
   if (K) {
      last_edge_Kptr = &last_edge_K;
      next_edge_Kptr = &next_edge_K;
   }

   Vec2 last_edge_force = edge_force(last_edge(0), edge_vector(q,0), last_edge_Kptr);   
   Vec2 next_edge_force;

   // Todo; refactor an assemble over edges

   for (Eigen::Index i = 0; i < num_nodes; ++i){
      next_edge_force = edge_force(next_edge(i), edge_vector(q,next_edge(i)), next_edge_Kptr);
      F.col(i) = next_edge_force - last_edge_force 
                  + m_[i] * g;

      last_edge_force = next_edge_force;

      if (K) {
         K->diag(i) = -next_edge_K - last_edge_K;
         if (i < num_nodes - 1) K->upper(i) = next_edge_K;

         last_edge_K = next_edge_K;
      }

   }

}

void LineModel::residual(const Vec& q_flat, Vec& r_flat, SymmBlockTriMat* jac) const {

   assert(r_flat.size() == q_flat.size());

   Eigen::Map<const Mat2X> q(q_flat.data(), 2, q_flat.size()/2);
   Eigen::Map<Mat2X> r(r_flat.data(), 2, r_flat.size()/2);

   assemble(q, r, jac);

}

// Generated by Claude:
// 
// A non-slack starting shape for the static solver. Every edge gets length
// stretch * l_e, where l_e is the shorter of its main and backup rest lengths.
// If the span is long enough the nodes lie on the straight chord; otherwise the
// chain forms a V hanging below the chord, with the kink placed exactly on a node
// so every edge lies on a straight leg and keeps its full length.
Vec LineModel::static_solver_initial_guess() const {

   const double stretch = 1.01;
   const Eigen::Index num_edges = line_.num_elements();
   const Eigen::Index num_nodes = num_edges - 1;   // free nodes, anchors excluded

   std::vector<double> l(num_edges);
   for (Eigen::Index e = 0; e < num_edges; e++)
      l[e] = std::min(line_.l_main[e], line_.l_backup[e]);

   const Vec2 chord = anchor_right_ - anchor_left_;
   const double D = chord.norm();
   const Vec2 u = chord / D;

   double total = 0.0;
   for (double le : l) total += le;

   Vec q(2 * num_nodes);
   Eigen::Map<Mat2X> Q(q.data(), 2, num_nodes);

   // Straight chord: stretch the chain uniformly to fit the span
   if (D >= stretch * total) {
      double s = 0.0;
      for (Eigen::Index i = 0; i < num_nodes; i++) {
         s += l[i];
         Q.col(i) = anchor_left_ + (s / total) * chord;
      }
      return q;
   }

   // V shape: kink at the node closest to half the rest length
   Eigen::Index kink = 0;
   double A = 0.0;
   while (kink < num_nodes - 1 && A + l[kink] < 0.5 * total) A += l[kink++];
   A = stretch * (A + l[kink]);            // left leg: edges 0..kink
   const double B = stretch * total - A;   // right leg: the remaining edges
   assert(std::abs(A - B) <= D);           // the triangle (A, B, D) must exist

   // Kink position from the triangle: a along the chord, h perpendicular to it
   const double a = (A * A - B * B + D * D) / (2.0 * D);
   const double h = std::sqrt(A * A - a * a);
   Vec2 n(-u.y(), u.x());
   if (n.dot(params_.gravity) < 0.0) n = -n;   // hang towards gravity
   const Vec2 apex = anchor_left_ + a * u + h * n;

   double s = 0.0;
   for (Eigen::Index i = 0; i < num_nodes; i++) {
      s += stretch * l[i];
      Q.col(i) = (i <= kink) ? Vec2(anchor_left_ + (s / A) * (apex - anchor_left_))
                             : Vec2(apex + ((s - A) / B) * (anchor_right_ - apex));
   }
   return q;
}


bool LineModel::both_neighboring_edges_slack_flat(const Vec& q) const {

   Eigen::Map<const Mat2X> Q(q.data(), 2, q.size()/2);
   return both_neighboring_edges_slack(Q);

}


bool LineModel::both_neighboring_edges_slack(CRef<Mat2X> q) const {

   const Eigen::Index num_edges = line_.num_elements();
   bool last_edge_slack = false;

   for (Eigen::Index e = 0; e < num_edges; e++) {
      double T = edge_force(e, edge_vector(q,e)).norm();

      bool this_edge_slack = T <= 1E-12;

      if (last_edge_slack && this_edge_slack) return true;

      last_edge_slack = this_edge_slack;
   }

   return false;

}

bool LineModel::static_solver(Vec& q, double tol) const {

   int maxsteps = 1000;
   double reduce_alpha = 0.9;

   Vec r(q.size());
   Vec dq(q.size()), qnew(q.size()); 
   SymmBlockTriMat Jac(q.size()/2);

   for (int i = 0; i < maxsteps; i++) {
       residual(q, r, &Jac);

       if (r.norm() < tol) { 
          std::cout << "converged in " << i << " iterations\n"; 
          return true; }

       Jac.solve(dq, -r);

       double alpha = 1;
       qnew = q + alpha*dq;

       // Linesearch to avoid slack edges.
       while ( both_neighboring_edges_slack_flat(qnew) ){
          alpha *= reduce_alpha;

          if (alpha < 1e-10) return false; // The solver didn't take a step

          qnew = q + alpha*dq;
       }

       q = qnew;

   }

   return false;

}


void LineModel::rhs(double t, const Vec& z, Vec& dz) const {

   assert(z.size() ==  dz.size());
   assert(&z != &dz);

   Eigen::Index n_nodes = z.size()/4;

   Eigen::Map<const Mat2X> q(z.data(), 2, n_nodes);             // First 2*n_nodes entries
   Eigen::Map<const Mat2X> v(z.data() + 2*n_nodes, 2, n_nodes); // Last 2*n_nodes entries

   Eigen::Map<Mat2X> dq(dz.data(), 2, n_nodes);             // First 2*n_nodes entries
   Eigen::Map<Mat2X> dv(dz.data() + 2*n_nodes, 2, n_nodes); // Last 2*n_nodes entries

   rhs(q, v, dq, dv);

}


void LineModel::rhs(CRef<Mat2X> q, CRef<Mat2X> v, Ref<Mat2X> dq, Ref<Mat2X> dv) const {

   // Compute forces
   assemble(q, dv); // No Jacobian for now

   // Set change in positions based on velocity
   dq = v; 

   // Set change in velocities based on forces
   Eigen::Map<const Eigen::RowVectorXd> m(m_.data(), m_.size());
   dv.array().rowwise() /= m.array();

}
